### PR TITLE
Use bin wrapper global option

### PR DESCRIPTION
**Pull request by nervo**

### CODE REVIEW

**Comment by shinnn** [comment]
Can I ask why? All the other *-bin modules in this organization don't use `global` option.

**Comment by kevva** [comment]
optipng-bin does. Doesn't really remember why I merged this though.

**Comment by shinnn** [comment]
#### Pros:

* Users can use actually executable build installed in their environments.
  * Maybe this solves the problems on some Linux. e.g. imagemin/imagemin#77

#### Cons:

* Maybe it causes some kind of problems like [this](https://github.com/sindresorhus/pageres/issues/143#issuecomment-64529374).

**Comment by kevva** [comment]
We have a '.version()` method though if we really need it.

**Comment by shinnn** [comment]
True.

**Comment by sindresorhus** [comment]
@kevva I don't think we should use the `global` option anywhere. It only causes problems, as we've experienced with `pageres` and broken global phantomjs installs.

**Comment by kevva** [comment]
Yeah, but sometimes our binary and the build fails. We don't depend on any specific version apart from some of our bin-wrappers so it makes sense to use the global options in some cases.

**Comment by sindresorhus** [comment]
@kevva Ok, so the `global` option uses the global binary as a last resort? I thought it was the other way around.

**Pull request merged**
