### PR TITLE
Added FreeBSD x64 jpegtran binary

### PR DESCRIPTION
**Pull request by AnatolyRugalev**

### CODE REVIEW

**Comment by Temarie** [comment]
:+1:

**Comment by enaza** [comment]
::+1::

**Comment by hutsi** [comment]
:+1:

**Comment by HUNTERxp** [comment]
+1

**Comment by Singularity303** [comment]
:+1:

**Comment by AnatolyRugalev** [comment]
Thank you very much for that!

**Comment by kevva** [comment]
Published to npm!

**Pull request merged**
